sudo: required

services:
  - docker

dist: xenial

language: python
python:
  - "3.6"

install:
 - ./run --isolate --background
 - npm install -g apidoc
 - npm run apidoc
 - npm install -g eslint
 - pip install -r test/requirements.txt

script:
 - npm run lint
 - test/check-style
 - ./wait-for-api || { docker ps; docker logs cacophony-api; exit 1; }
 - cd test && pytest
 - docker exec -it cacophony-api /app-isolated/node_modules/.bin/sequelize db:migrate:undo --config /app-isolated/config/app_test_default.js --migrations-path /app-isolated/migrations
