sudo: required

services:
  - docker

dist: xenial

language: python
python:
  - "3.6"

install:
 - ./run --isolate --background
 - npm install -g eslint
 - pip install -r test/requirements.txt

script:
 - npm run lint
 - ./wait-for-api || { docker ps; docker logs cacophony-api; exit 1; }
 - cd test && pytest -s
